#!/usr/bin/env bash
# Configures UFW to forward port 8080 to port 80

apt-get update -y
apt-get install ufw -y

ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 80
ufw allow 443

ufw allow 8080

# Enable port forwarding from 8080 to 80
echo '
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
' > /etc/ufw/before.rules

ufw --force enable
